In [333]:
import pandas as pd
import numpy as np

In [334]:
np.random.seed(42)

In [335]:
fastball_speed=np.random.randint(90,106,size=500)

In [336]:
tommy_john=np.where(fastball_speed>96,np.random.choice([0,1],size=500,p=[0.3,0.7]),0)

In [337]:
d={'fastball_speed':fastball_speed,'tommy_john':tommy_john}

In [338]:
df=pd.DataFrame(data=d)

In [339]:
df

fastball_speed  tommy_john
0                96           0
1                93           0
2               102           1
3               104           1
4               100           0
..              ...         ...
495             104           1
496              92           0
497             101           1
498              90           0
499              93           0

[500 rows x 2 columns]

In [340]:
X=df[['fastball_speed']]

In [341]:
y=df[['tommy_john']]

In [342]:
#normal train test split

In [343]:
from sklearn.model_selection import train_test_split

In [344]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [345]:
from sklearn.linear_model import LogisticRegression

In [346]:
lr=LogisticRegression()

In [347]:
lr.fit(X_train,y_train.values.ravel())

LogisticRegression()

In [348]:
lr.score(X_test,y_test)

0.81

In [349]:
X2_train,X2_test,y2_train,y2_test=train_test_split(X,y,test_size=0.2,random_state=25)

In [350]:
lr.fit(X2_train,y2_train.values.ravel())

LogisticRegression()

In [351]:
lr.score(X2_test,y2_test)

0.8

In [352]:
#basic cross val

In [353]:
from sklearn.model_selection import cross_val_score

In [354]:
cvscore=cross_val_score(lr,X,y.values.ravel(),cv=10)

In [355]:
cvscore

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [356]:
np.average(cvscore)

0.756

In [357]:
np.std(cvscore)

0.04270831300812523

In [358]:
#define standard kfold

In [359]:
from sklearn.model_selection import KFold

In [360]:
kf=KFold(n_splits=15, shuffle=True,random_state=42)

In [361]:
kfscore=cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='f1')

In [362]:
kfscore2=cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='accuracy')

In [363]:
kfscore

array([0.66666667, 0.82758621, 0.72727273, 0.7027027 , 0.6875    ,
       0.72727273, 0.74074074, 0.72      , 0.66666667, 0.60869565,
       0.66666667, 0.63157895, 0.64516129, 0.66666667, 0.6       ])

In [364]:
np.average(kfscore)

0.6856785107611354

In [365]:
np.std(kfscore)

0.05620337068328654

In [366]:
from sklearn.model_selection import StratifiedKFold

In [367]:
kf3 = StratifiedKFold(n_splits=10,shuffle=True,random_state=11)

In [368]:
kfscore3=cross_val_score(lr,X,y.values.ravel(),cv=kf3)

In [369]:
kfscore3

array([0.66, 0.76, 0.76, 0.8 , 0.8 , 0.74, 0.76, 0.74, 0.78, 0.76])

In [370]:
np.average(kfscore3)

0.756

In [371]:
np.std(kfscore3)

0.03773592452822642

In [372]:
from sklearn.preprocessing import StandardScaler

In [373]:
scaler=StandardScaler()

In [374]:
from sklearn.pipeline import make_pipeline

In [375]:
pipe1=make_pipeline(scaler,lr)

In [376]:
pipe1.fit(X_train,y_train.values.ravel())

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [377]:
scorespipe=cross_val_score(pipe1,X,y.values.ravel(),cv=10)

In [378]:
scorespipe

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [379]:
np.average(scorespipe)

0.756

In [380]:
np.std(scorespipe)

0.04270831300812523